---
- name: Install clickhouse packages
  become: true
  ansible.builtin.dnf:
    name:
      - clickhouse-common-static-{{ clickhouse_version }}.rpm
      - clickhouse-client-{{ clickhouse_version }}.rpm
      - clickhouse-server-{{ clickhouse_version }}.rpm
  notify: Start clickhouse service