---
- name: Add download tasks
  import_tasks: download/{{ ansible_pkg_mgr }}.yml

- name: Add install tasks
  import_tasks: install/{{ ansible_pkg_mgr }}.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add configure tasks
  import_tasks: configure.yml